export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST"
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS"
export const USER_FETCH_FAILURE = "USER_FETCH_FAILURE"

export const USER_ADD_REQUEST = "USER_ADD_REQUEST"
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS"
export const USER_ADD_FAILURE = "USER_ADD_FAILURE"

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE"

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE"

export const SHOW_ADD_MODAL = "SHOW_ADD_MODAL"
export const CLOSE_ADD_MODAL = "CLOSE_ADD_MODAL"

export const SHOW_EDIT_MODAL = "SHOW_EDIT_MODAL"
export const CLOSE_EDIT_MODAL = "CLOSE_EDIT_MODAL"

export const SHOW_DELETE_MODAL = "SHOW_DELETE_MODAL"
export const CLOSE_DELETE_MODAL = "CLOSE_DELETE_MODAL"

